name: lahme2
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.6.0
  - blas=1.0
  - boost-cpp=1.82.0
  - bottleneck=1.4.2
  - brotli-python=1.0.9
  - c-ares=1.34.5
  - cairo=1.16.0
  - contourpy=1.3.1
  - cycler=0.11.0
  - dav1d=1.2.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.55.3
  - freetype=2.13.3
  - fribidi=1.0.10
  - gdk-pixbuf=2.42.10
  - gettext=0.21.0
  - giflib=5.2.2
  - glib=2.84.2
  - glib-tools=2.84.2
  - graphite2=1.3.14
  - graphviz=12.2.1
  - gts=0.7.6
  - harfbuzz=10.2.0
  - joblib=1.4.2
  - jpeg=9e
  - kiwisolver=1.4.8
  - lcms2=2.16
  - lerc=4.0.0
  - libavif=1.1.1
  - libboost=1.82.0
  - libcurl=8.14.1
  - libdeflate=1.22
  - libgd=2.3.3
  - libglib=2.84.2
  - libltdl=2.4.3a
  - libnghttp2=1.57.0
  - libopenblas=0.3.29
  - libpng=1.6.39
  - librsvg=2.56.3
  - libssh2=1.11.1
  - libtiff=4.7.0
  - libtool=2.5.4
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lz4-c=1.9.4
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - networkx=3.4.2
  - nspr=4.36
  - nss=3.89.1
  - numexpr=2.11.0
  - numpy=2.2.5
  - numpy-base=2.2.5
  - openjpeg=2.5.2
  - packaging=25.0
  - pandas=2.3.1
  - pango=1.50.7
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.1
  - pixman=0.40.0
  - poppler=24.09.0
  - poppler-data=0.4.12
  - pygraphviz=1.14
  - pyparsing=3.2.0
  - python=3.10.18
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - pytz=2025.2
  - scikit-learn=1.7.1
  - scipy=1.15.3
  - setuptools=72.1.0
  - six=1.17.0
  - tabulate=0.9.0
  - threadpoolctl=3.5.0
  - tornado=6.5.1
  - unicodedata2=15.1.0
  - wheel=0.45.1
  - pip:
      - git+https://github.com/Hanqi-Angelina/kerpy.git
      - pydot==4.0.1
